version: '3.9'
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - .data/mongodb:/data/db:rw
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=siakoo
      - MONGO_INITDB_ROOT_PASSWORD=password
    